
package com.test.client;

import com.test.model.Message;
import com.test.model.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param name string text with a name
     * @return
     *     returns com.test.model.Message
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://service.test.com/", className = "com.test.model.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://service.test.com/", className = "com.test.model.GreetResponse")
    @Action(input = "http://service.test.com/HelloService/greetRequest", output = "http://service.test.com/HelloService/greetResponse")
    public Message greet(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
